### ISSUE TITLE
和Scrollview 有冲突怎么处理

### ISSUE THREAD

**Issue by anjiao** [Carbs0126/NumberPickerView#1]
RT

**Comment by Carbs0126** [comment]
感谢你的issue，现在已经修复了，在onTouch的down事件中添加以下代码，问题解决。<br>`getParent().requestDisallowInterceptTouchEvent(true);`<br>
在工程中更新一下依赖的版本号即可<br>`compile 'cn.carbswang.android:NumberPickerView:1.0.3'`

**Comment by anjiao** [comment]
嗯 谢谢
