### ISSUE TITLE
设置动态显示数据时可以更换最小值么？

### ISSUE THREAD

**Issue by huayicheng2015** [Carbs0126/NumberPickerView#10]
在README.MD中：
>
2)若设置的数据(String[] mDisplayedValues)会改变，可以使用如下组合方式进行设置：（与NumberPicker的更改数据方式一致）
```java
        int minValue = getMinValue();
        int oldMaxValue = getMaxValue();
        int oldSpan = oldMaxValue - minValue + 1;
        int newMaxValue = display.length - 1;
        int newSpan = newMaxValue - minValue + 1;
        if (newSpan > oldSpan) {
            setDisplayedValues(display);
            setMaxValue(newMaxValue);
        } else {
            setMaxValue(newMaxValue);
            setDisplayedValues(display);
        }
```
或者直接使用NumberPickerView提供的方法：<br>
    `refreshByNewDisplayedValues(String[] display)`<br>
使用此方法时需要注意保证数据改变前后的minValue值不变，以及设置的display不能够为null，且长度不能够为0。

如果使用与NumberPicker的更改数据方式一致的方法，可以更改最小值么？

**Comment by Carbs0126** [comment]
应该是可以的，但是我没有过多的对更改最小值进行测试，一般情况下固定最小值并使用
```
refreshByNewDisplayedValues(String[] display)
```
就能满足需要。

另外，好像NumberPicker是不能够设置最小值为负值的，只能大于等于0，动态的更改最小值后，小于最小值的那部分对应的值好像就不显示了。

对于NumberPickerView动态的改变最小值，我再进一步测测。如果需要动态的“去掉”数据list的起始的某一部分，可以使用refreshByNewDisplayedValues(String[] display)，传入的参数为“去掉“头部部分数据的剩余部分

**Comment by huayicheng2015** [comment]
目前可以肯定我使用的数据全是正数，且我确实需要更换最小值，如原显示数据为1，2，3，4，5，6，现在欲显示的数据为7，8，9，10，11，12

**Comment by Carbs0126** [comment]
刚才测试了一下，可以这样：
更新函数：
```java
//输入一个最小值，输入连续的数，最大值自动按照（最小值+字符串数组长度-1）来确定
private void updateData(int newMinValue, String[] display) {
        int oldMinValue = picker.getMinValue();
        int oldMaxValue = picker.getMaxValue();
        int oldSpan = oldMaxValue - oldMinValue + 1;

        int newMaxValue = newMinValue + display.length - 1;
        int newSpan = newMaxValue - oldMinValue + 1;

        if (newSpan > oldSpan) {
            picker.setMinValue(newMinValue);
            picker.setDisplayedValues(display);
            picker.setMaxValue(newMaxValue);
        } else {
            picker.setMinValue(newMinValue);
            picker.setMaxValue(newMaxValue);
            picker.setDisplayedValues(display);
        }
    }
```

调用：
updateData(1,new String[]{"1","2","3","4","5","6"});
updateData(7,new String[]{"7","8","9","10","11","12","13","14"});

回调：//与之前相同
@Override
    public void onValueChange(NumberPickerView picker, int oldVal, int newVal) {
        String[] content = picker.getDisplayedValues();
        if (content != null)
            Toast.makeText(getApplicationContext(),"oldVal : " + oldVal + " newVal : " + newVal + "\n" +
                    getString(R.string.picked_content_is) + content[newVal - picker.getMinValue()], Toast.LENGTH_SHORT)
                    .show();
    }

**Comment by huayicheng2015** [comment]
```Java
int newSpan = newMaxValue - oldMinValue + 1
```
是不是应该改为
```Java
int newSpan = newMaxValue - newMinValue + 1
```

**Comment by Carbs0126** [comment]
对，我刚才测了一下，这个地方写错了

**Comment by huayicheng2015** [comment]
```Java
if (newSpan > oldSpan) {
            picker.setMinValue(newMinValue);
            picker.setDisplayedValues(display);
            picker.setMaxValue(newMaxValue);
}
```
是不是应该改为
```Java
if (newSpan > oldSpan) {
            picker.setMinValue(newMinValue);
            picker.setMaxValue(newMaxValue);
            picker.setDisplayedValues(display);
}
```

**Comment by Carbs0126** [comment]
你的代码出错了吗？
```
            picker.setMaxValue(newMaxValue);
            picker.setDisplayedValues(display);
```
这两行代码如果交换位置，就可能出现"越界"，因为如果新的数据的长度小于旧的数据，如果先设置maxValue，此时没有设置旧的数据displayvalues，maxValue可能就会超过旧数据的长度边界值，因此不要交换两者的顺序，这和android自带的NumberPicker的用法是一致的

**Comment by huayicheng2015** [comment]
如果按我的改法就出现了：java.lang.IllegalArgumentException: (maxValue - mMinValue + 1) should not be greater than mDisplayedValues.length now  (maxValue - mMinValue + 1) is 6 and mDisplayedValues.length is 4
如果按你的就出现了： java.lang.IllegalArgumentException: mMaxValue - mMinValue + 1 should not be greater than mDisplayedValues.length, now ((mMaxValue - mMinValue + 1) is 12 newDisplayedValues.length is 6, you need to set MaxValue and MinValue before setDisplayedValues(String[])

**Comment by huayicheng2015** [comment]
都是从9，10，11，12---->1,2,3,4,5,6

**Comment by huayicheng2015** [comment]
完整步骤：
1,2,3,4,5,6,7,8,9,10,11,12---->1,2,3,4,5,6---->9,10,11,12(---->1,2,3,4,5,6)
括号中的崩溃

**Comment by Carbs0126** [comment]
嗯，我刚才测了一下，确实是出错，这和设置minValue、maxValue、displayValues的顺序有关系，我稍微改了一下调用顺序，避免了这个出错问题，如下：
```
        if (newSpan > oldSpan) {
            picker.setDisplayedValues(display);//更改这两个函数的调用顺序
            picker.setMinValue(newMinValue);//更改这两个函数的调用顺序
            picker.setMaxValue(newMaxValue);
        } else {
            picker.setMinValue(newMinValue);
            picker.setMaxValue(newMaxValue);
            picker.setDisplayedValues(display);
        }
```
我这边暂时是不出错了，异常主要是因为minValue的值先改变了，再设置displayValue时会对比检查其长度与(maxValue-minValue)，如果后者大于前者，就会主动抛出异常，这样也是便于差错
