### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by Qingtian239113** [Carbs0126/NumberPickerView#11]
Only the original thread that created a view hierarchy can touch its views.

**Comment by Carbs0126** [comment]
你查一下是不是在布局文件中添加此属性了？
```
app:npv_RespondChangeInMainThread="true"
```
如果添加了并且值为false，就会在子线程中响应onChange，不添加此属性或者添加此属性值为true，则是在主线程中响应onChange.
另外，如果是使用的dependencies，请更新到最新的版本，如下：
```
compile 'cn.carbswang.android:NumberPickerView:1.1.0'
```

**Comment by Carbs0126** [comment]
这个问题是在子线程中响应了onchange，同时在onchange中操作了UI，导致了这个问题
