### ISSUE TITLE
能不能不要循环显示

### ISSUE THREAD

**Issue by huayicheng2015** [Carbs0126/NumberPickerView#15]
### 当待显示的数到一定范围时，就会被循环显示。比如，待显示的数为1，2，3，4，5，6，7，8，9，10，11，12，显示效果是在12下面会出现1，现在我希望12下面宁愿是空白，我要选1时，我宁愿往下滑。

**Comment by huayicheng2015** [comment]
### 再看一会儿文档再来

**Comment by Carbs0126** [comment]
我说怎么找不到问题了。
这样，你可以设置此属性：
```
npv_WrapSelectorWheel 将其设置为false，false就不会循环了，默认true循环显示
```
