### ISSUE TITLE
控件的不可用状态没有处理

### ISSUE THREAD

**Issue by wulaoh** [Carbs0126/NumberPickerView#16]
当调用setEnabled(false)把控件设置为不可用状态后，内部没有做相关的处理。
1.  onTouchEvent 事件应该在不可用时不处理
2. setSelectedTextColor，setNormalTextColor， 应该可以设置selector
3. 字体大小，代码中无法设置，只可以在xml设置，有点不方便。

**Comment by Carbs0126** [comment]
嗯，感谢关注，您提的这几项我当时确实都忽视了，后续我会将这三项功能逐渐加上，非常感谢您的issue

**Comment by wulaoh** [comment]
多谢作者回复，非常感谢您的工作，如要修订的话，是否可以加入下面的问题调整，
1. 针对View 的 layout_padding， 代码没有做处理
2. 是否开放一些成员变量及方法的访问级别到protected,方便override

**Comment by Carbs0126** [comment]
感谢您的关注！
1.我刚才看了一下代码，View的padding中，我只处理了左右padding，上下padding忘了处理了，谢谢提醒！
2.开放属性以及方法访问级别我之前没有考虑到，后续版本会更改的。

我之前开发过程中这几个问题都没有考虑到，多谢您的提醒，谢谢
