### ISSUE TITLE
How to use a different Typeface?

### ISSUE THREAD

**Issue by 4goodapp** [Carbs0126/NumberPickerView#17]
I to change the default typeface/font for NumberPickerView?
I want use a custom font.

**Comment by Carbs0126** [comment]
sorry i have not add customizing font function, you can custom font in NumberPickerView by using code:
```
mPaintText.setTypeFace(...);
```
when `mPaintText` is initialized.

i will add this function later

**Comment by 4goodapp** [comment]
Thanks, for fast answer.
I try to edit the file within Android Studio but I can't edit the file. I'ts locked :(
Any Idea about this?

**Comment by 4goodapp** [comment]
After some search, I manage to import the project as module and was able to edit the file but what I should put in  `mPaintText.setTypeFace(...);` ? 
I tried those but didn't work:

`        mPaintText.setTypeface(Typeface.create("2Toon", Typeface.BOLD));
        mPaintText.Typeface.createFromAsset(getContext().getAssets(), "2Toon.ttf");
        mPaintText.setTypeface(Typeface.createFromAsset(getContext().getAssets(),"fonts/2Toon"));
`

**Comment by Carbs0126** [comment]
sorry for not replying in time, you can add a method 
```
public void setContentTextTypeface(Typeface typeface){
        mPaintText.setTypeface(typeface);
    }

    public void setHintTextTypeface(Typeface typeface){
        mPaintHint.setTypeface(typeface);
    }
```
and invoke this method outside in oncreate method , if you want to change typeface dynamicly, using mNumberPickerView.invalidate( ) after using this method

**Comment by 4goodapp** [comment]
No Problem :) 
I solved the problem by adding:
`        mPaintText.setTypeface(Typeface.createFromAsset(context.getAssets(),"fonts/MyFont.ttf"));
`
It worked for me. I don't know if it's a good practice to do it in that way though.

**Comment by Carbs0126** [comment]
if you have used MyFont.ttf, you can use a static value to refer to this MyFont.ttf, in this way you can avoid memory leak, because every time you use 
``` Typeface.createFromAsset(context.getAssets(),"fonts/MyFont.ttf")```
MyFont.ttf will be created again and added into memory.

**Comment by 4goodapp** [comment]
I don't understand what you mean by "...use a static value to refer to this MyFont.ttf".
How can I use a static value to refer to the custom font I want use?

**Comment by Carbs0126** [comment]
i mean you can use cache to refer to  MyFont.ttf, in this way, if you use  MyFont.ttf again, you can get  MyFont.ttf from cache,
just like 
```
public static Typeface cache = Typeface.createFromAsset(context.getAssets(),"fonts/MyFont.ttf")

mPaintText.setTypeface(cache);
```
this will avoid memory leak

**Comment by 4goodapp** [comment]
Ah okay, I got it now. I'll change it.
But compared to [your solution],    what are the differences/advantages?(https://github.com/Carbs0126/NumberPickerView/issues/17#issuecomment-256274278)

**Comment by Carbs0126** [comment]
if there are many numberpickerviews in you app( or other views which use MyFont.ttf), there will be many copy of MyFont.ttf, but in fact only one MyFont.ttf is enough

**Comment by 4goodapp** [comment]
Cool, I got it :) Thank you very much.

Off Topic:
Is their a way to display the selected numbers while scrolling?
I tried to put it in the the `onScrollStateChange` methode but it randomly crash my app. 

Like in this gif:
http://i.imgur.com/d3ZMjss.gif

**Comment by Carbs0126** [comment]
i have not add this function, if you need this function now, you can add some code into 
```
calculateFirstItemParameterByGlobalY()
``` 
and get the index of current selected item by ```mCurrDrawFirstItemIndex``` and ```mCurrDrawFirstItemY```, and set this index value to another value such as 'currSelected', and use a 'prevSelected' to store the last selected one in scrolling, if currSelected != prevSelected, then number changed. i will add this function later  :)

**Comment by Carbs0126** [comment]
i have added a method 
  ```java
    picker.setOnValueChangeListenerInScrolling(...);
  ```
you can get changed value while in scrolling

and i have also added two methods for changing typeface of text/hint in NumberPickerView,
just update dependence version of NumberPickerView to 1.1.1

**Comment by 4goodapp** [comment]
Oh, Great, 
I just try it , it's working but the scrolling but the scrolling is not smooth. 

`    @Override
    public void onValueChangeInScrolling(NumberPickerView picker, int oldVal, int newVal) {
        myChosedNumber.setText(picker.getContentByCurrValue());
     }`

Is there a better way to make it as smooth as in [the gif](http://i.imgur.com/d3ZMjss.gif)

**Comment by Carbs0126** [comment]
this callback will be invoked once as number value changed for 'one item', and this callback runs in main thread , if you want to do some complicated work  in this callback such as play sound, it may make scrolling lag. To make scrolling smoothly you can use handler to send message in this callback ,or make callback tasks run in a new thread, if it still lag, you can send your code to me ,and maybe i can refine this project according to your code

**Comment by 4goodapp** [comment]
Hi, I sent just you the project via email,
I've tried to put the code in a `Runnable`  as well in a `AsyncTask` but it was still laggy.

I planned to add a scrolling sound but It's not much of a big deal if it may create (lag) problems...

If you need any info, let me know.

**Comment by 4goodapp** [comment]
And by the way, I've try the project in that gif on my phone and it was working smoothly, just like in the gif.

I found that project [from here](https://github.com/iwhys/AndroidWheel/issues), Just in case it may help.

**Comment by tinsukE** [comment]
@Carbs0126 Can you update the version in the README file to 1.1.1?

I was trying to branch the repo to add the Typeface functionality, but saw that it was already implemented in this version (which is not refereed to anywhere).

**Comment by rohankandwal** [comment]
I have created a fork of the project which allows custom font loading from xml itself. I will be glad if you can take a look at it.
https://github.com/rohankandwal/NumberPickerView
