### ISSUE TITLE
setMinValue的bug

### ISSUE THREAD

**Issue by zsyh** [Carbs0126/NumberPickerView#19]
final String[] mDisplayValues=new String[]{"今天","明天","后天"};
numberPicker.setDisplayedValues(mDisplayValues);
numberPicker.setMinValue(0);
numberPicer.setMaxValue(2);
显示正常。

但是，
numberPicker.setMinValue(1);//代码中需要动态调节minValue进行限位
发生了两个问题：
1、由于限位造成的value改变，并没有触发onValueChanged事件
2、在numberPicker中，预期效果应该显示为 明天、后天，实际显示为 今天、明天
并且，UI显示的"今天"所对应的value为“明天”(1)，也就是说，UI显示的值与实际的value出现了不一致的情况,实际的值是正确的,而UI显示的是错误的。
一个好用的控件，其显示范围应该能由setMinValue()和setMaxValue()来决定。

**Comment by Carbs0126** [comment]
你好，刚看到issue，此控件的api设计和numberpicker的api基本相同，numberpicker的setminvalue没有因minvalue的改变而改变最小显示项，为了和numberpicker保持一致，没有在此函数中添加其他功能。

你刚才说的两个问题：
1.限位造成此控件数组content改变，确实不响应onValueChanged，我觉得暂时可以通过响应造成限位的触发事件来添加相关的change事件
2.setminvalue只是用来设置第一个显示单位的对应数值，而非从mDisplayValues的内容中去截取，和numberpicker一致。如果想要纠正UI显示，即去掉"今天”，暂时的解决方法是可以根据当前想要截取的起始值来主动截取mDisplayValues，然后使用refreshByNewDisplayedValues(String[] display)刷新content内容，如果想要使得转换具有动画效果，可以接着添加smoothScrollToValue(int fromValue, int toValue, boolean needRespond)方法。
你提出的问题我后续会添加相关内容，多谢
