### ISSUE TITLE
Drag to scroll doesn't work

### ISSUE THREAD

**Issue by Elektroktay** [Carbs0126/NumberPickerView#2]
I can't drag to scroll, and I don't see anything about dragging or flinging in the readme file even though it promises better flinging by adjusting friction...

**Comment by Carbs0126** [comment]
1. I have tested again, and on Android 4.1, 4.2.2, 5.1 it works pretty well and can be drag to scroll, can you tell me the Android version of your device? Readme file contains gifs which display the scrolling and flinging. 
2.If you want to modify friction, you can set friction by using code `mNumberPickerView.setFriction(ViewConfiguration.get(mContext).getScrollFriction() * 2);`, in this way, the NumberPickerView's friction will be twice as much as former, then fling verlocity will be smaller

**Comment by Carbs0126** [comment]
Thanks for your issue, maybe you use this view in ScrollView? Now the bug of ‘cannot scroll in ScrollView’ has been fixed, cause I add the code below in `onTouch(MotionEvent e)`.<br>`getParent().requestDisallowInterceptTouchEvent(true);`<br>
You can update the dependence version to 1.0.3<br>`compile 'cn.carbswang.android:NumberPickerView:1.0.3'`

**Comment by Elektroktay** [comment]
Sorry for not being clear. I was using the NumberPicker inside a NestedScrollView, and your update fixed my issue. Thank you so much! :)

**Comment by Carbs0126** [comment]
Thank you for your consideration
