### ISSUE TITLE
Stop scrolling animation when button press 

### ISSUE THREAD

**Issue by alexgomes09** [Carbs0126/NumberPickerView#22]
THANK YOU SO MUCH for sharing and your hard work. Would like to add a bit more enhancement :)

Maybe, it's better to keep this method public so we can call when user press a button

Use case - 
User (fling) scrolling > Quickly press OK/Pick button > number picker should stop at that value and stop scrolling animation

Making this method public already does stop the scroll animation and stop at picked value. :+1: 

```
public void stopScrolling() {
        if (mScroller != null) {
           ...
        }
    }
```

**Comment by Carbs0126** [comment]
thank you for your suggestion, this method will make picker view stop immediately with out refine positions of its items, and i made this method public , and added a new method to [stopScrolling + refine Positions of Its Items]

```
    public void stopScrollingAndCorrectPosition(){
         stopScrolling();
         if (mHandlerInNewThread != null){
             mHandlerInNewThread.sendMessageDelayed(getMsg(HANDLER_WHAT_REFRESH), 0);
         }
     }
```

**Comment by Carbs0126** [comment]
Thank you for your suggestion ! by the way, i have not update the bintray
