### ISSUE TITLE
Fade top and bottom of view

### ISSUE THREAD

**Issue by alexgomes09** [Carbs0126/NumberPickerView#23]
Thanks again for such a great library. You got any idea how I can fade/alpha top and bottom of view. So just like native number picker but I want to be able to increase/decrease that fade. 

Trying / playing with mPaintText right now. Not sure if this would do or I may need to create another paint object. Let me know if you got any idea. :)

**Comment by alexgomes09** [comment]
I was some how able to give fading edge by overriding these two methods in NumberPicker.java

`@Override
    protected float getBottomFadingEdgeStrength() {
        return 1.0f;
} `
` @Override
    protected float getTopFadingEdgeStrength() {
        return 1.0f;
    }
`

and then from xml I gave
 ` android:fadingEdgeLength="133dp"`
        `android:requiresFadingEdge="vertical"`

Not sure this is the best option but kinda works. Let me know if you got any better idea.

**Comment by Carbs0126** [comment]
sorry for not replying you intime. i just try your code and it works well, and i have not think out any other good idea, thanks for your good idea!

**Comment by snok3r** [comment]
@alexgomes09 thank sooo much you! I was looking for the same thing. Have you encountered any bugs with this method since then?
