### ISSUE TITLE
Set Default value on initialize

### ISSUE THREAD

**Issue by alexgomes09** [Carbs0126/NumberPickerView#24]
Enhancement: 

I am trying to find a way to set default value. 

use case :-
Current time is 3:06. When user go to specific screen, dev can take system time and feed that into numberpicker, so number picker would be set like 3:06 instead of showing the first element of the array.

**Comment by alexgomes09** [comment]
Really sorry, I totally didn't see this helpful method `setDisplayedValuesAndPickedIndex` 
This method helped what I needed.

**Comment by Carbs0126** [comment]
you can just use `setValue()` after `setDisplayValues()`
