### ISSUE TITLE
请问为什么OnValueChangeListener中的onValueChange方法没有及时响应呢？

### ISSUE THREAD

**Issue by AngTtXu** [Carbs0126/NumberPickerView#25]
OnValueChangeListener中的onValueChange方法每次都要在选中后间隔1秒左右才能响应，OnValueChangeListenerInScrolling的onValueChangeInScrolling方法及时响应了，但是只记录选中值的上一个值，因此两个监听都无法很好的及时确定选中的值，请问有什么方法可以解决吗？

**Comment by AngTtXu** [comment]
换成OnScrollListener()，问题解决，谢谢。

**Comment by Carbs0126** [comment]
不好意思没及时看到你的消息，感谢关注
