### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by shwetarc** [Carbs0126/NumberPickerView#33]
Can we give font to numberpicker?

**Comment by Carbs0126** [comment]
i did not provide function to set font, you can set font to Paint object in NumberPickerView

**Comment by shwetarc** [comment]
Can you Please provide syntax for paint?

**Comment by Carbs0126** [comment]
you can check this page to get some information:
https://github.com/Carbs0126/NumberPickerView/issues/17

**Comment by shwetarc** [comment]
Thanks..
