### ISSUE TITLE
怎么显示数字自动增长的NumberPickerView

### ISSUE THREAD

**Issue by klower1989** [Carbs0126/NumberPickerView#4]
例如我提供一个最小值 每次增加1最大值为30的纯数字NumberPickerView，我不想设置给NumberPickerView一个String类型的数组，该怎么弄？

**Comment by Carbs0126** [comment]
；会好意思回复的晚了。这个我没有考虑，因为首先我只是界定内容是string，并且没有去考虑string[] 中的内容遵从何种规律，否则做起来可能耦合性较高，所以没有考虑这种情况，只做了外界直接赋予String[]这种情况
