### ISSUE TITLE
初始化时要使用setDisplayedValues

### ISSUE THREAD

**Issue by liguanglong** [Carbs0126/NumberPickerView#40]
只想显示数字时用setMinValue()和setMaxValue()而不用setDisplayedValues()时会报错
Java代码：
 NumberPickerView numberPicker = (NumberPickerView) findViewById(R.id.picker);
        numberPicker.setMaxValue(10);
        numberPicker.setMinValue(0);
        numberPicker.setValue(2);
报错信息：
(maxValue - mMinValue + 1) should not be greater than mDisplayedValues.length now  (maxValue - mMinValue + 1) is 11 and mDisplayedValues.length is 1
而原生的NumberPicker做同样的设置不会报错

**Comment by MeowStone** [comment]
不理解这样的设计

**Comment by SZooo** [comment]
我也报了这个错，非常不顺手

**Comment by Carbs0126** [comment]
感谢各位关注。这样设计的原因是，暂时没有找到更合理的设计，现在这种设计是参考了Android的原生 NumberPicker的api，主要是为了保证更新数据时，数据的数量和显示范围的统一性问题。这种设计其实和原生的NumberPicker差不多一致。出错是因为设置的DisplayedValues的数目小于 max-min这个数

**Comment by Carbs0126** [comment]
所有的item的显示内容，都是字符串，此控件并不只是设计成显示数字，同时此控件的设计参考了android原生的NumberPicker，api的使用也是参考其用法，已使得将NumberPicker改为NumberPickerView时不需要做太多变动。
