### ISSUE TITLE
颜文字(Emoji)支持

### ISSUE THREAD

**Issue by clxy** [Carbs0126/NumberPickerView#43]
粗略的看下源代码，貌似不能简单的实现颜文字支持？
不知道是否可以提供些思路？
多谢！

**Comment by clxy** [comment]
搞定！

- 使用Android原生的Emoji Compat
- 设置TypeFace
`np.setContentTextTypeface(Typeface.createFromAsset(getContext().getAssets(), "NotoColorEmojiCompat.ttf"));`

**Comment by Carbs0126** [comment]
感谢您的关注！这个是很好，我之前也没想过emoji的问题，谢谢您！
