### ISSUE TITLE
我控件中只想显示一条数据用来滑动，如何去除顶部和底部默认黄色的横条？

### ISSUE THREAD

**Issue by yecal** [Carbs0126/NumberPickerView#44]
我控件中只想显示一条数据用来滑动，
如何去除选中项顶部和底部默认黄色的横条？

**Comment by yecal** [comment]
我控件中只想显示一条数据用来滑动，
如何去除选中项顶部和底部默认黄色的横条？
求大神帮助。

**Comment by Carbs0126** [comment]
可以设置属性
app:npv_ShowCount="1"
 <attr name="npv_ShowDivider" format="reference|boolean" />//是否显示两条divider，默认显示  这个设置为false
可以试试。没测过这种情况

**Comment by yecal** [comment]
app:npv_ShowCount="1"
这个我设置了，您下面写的：
//是否显示两条divider，默认显示 这个设置为false
这个是什么代码？没发全吗？麻烦发一下。万分感谢！

**Comment by Carbs0126** [comment]
npv_ShowDivider=“false” 试试

**Comment by yecal** [comment]
解决了，谢谢大神！！！
