### ISSUE TITLE
不知道是不是BUG

### ISSUE THREAD

**Issue by a453826252** [Carbs0126/NumberPickerView#45]
在xml文件中设置最小值和最大值的时候，如果没有设置npv_TextArray，会闪退，空指针异常。看了代码，发现最小值在里面只是用于数组下标的作用。而不是展示的作用。不知道是作者故意如此，还是一个bug

**Comment by Carbs0126** [comment]
你抛出的异常是不是NumberPickerView中抛出的？这个是主动抛出的，为的是max min 之间的范围不应当比 textArray的length大，否则就会主动跑异常
