### ISSUE TITLE
我想修改里面的字体

### ISSUE THREAD

**Issue by yecal** [Carbs0126/NumberPickerView#46]
现在列表中显示的10:30，中间的“:”这个符号太靠近下面了。我在软件中用了全局的字体。但是这儿没有自动替换。怎么样能给中间的“:”这个符号让处于中间呢？
注：
如果输入中文符的“：”，显示的时候效果会变成：“10：  30”
中间距离太大，求方案！谢谢各位大神！

**Comment by Carbs0126** [comment]
你找下view中的paint，有个专门“写字”的paint，改下这个paint的字体就可以了

**Comment by yecal** [comment]
大神，我找到paint了，paint怎么改啊？
没找到paint.set方法

**Comment by Carbs0126** [comment]
在numberpickerview的init方法中，你找下mPaintText，然后看看能不能设置上字体 

应该用下面的方法就可以
Typeface font = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD);
p.setTypeface( font );

字体最好是全局保存一个，否则可能有内存泄漏

**Comment by yecal** [comment]
好了，设置完了，谢谢大神！
顺便总结一下：
1.将NumberPickerView提取出来放到自己的项目中。
2.  大概将这些代码放在init()中的大概323行。
        Typeface typeFace =Typeface.createFromAsset(getContext().getAssets(),"PingFang Bold.ttf");
        mPaintText.setFlags(Paint.ANTI_ALIAS_FLAG);   //消除锯齿
        mPaintText.setTypeface(typeFace);
设置如上代码，其中PingFang Bold.ttf为我自己放在assets目录文件夹下面的字体。
3.注意修改xml文件中的引用名称等。

**Comment by Carbs0126** [comment]
我不是大神，只是菜鸟一枚。
写的很详细，谢谢！
之前看过文章说，字体好像不要创建太多，占内存，全局保存一份就可以，我没注意过。
