### ISSUE TITLE
"Only the original thread that created a view hierarchy can touch its views"

### ISSUE THREAD

**Issue by luizfp** [Carbs0126/NumberPickerView#5]
If I set a listener to `OnValueChangeListener` and then try to modify any view in the callback method, I get the well know android exception:

`android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.`

**Comment by Carbs0126** [comment]
that's because in NumberPickerView OnValueChangeListener is invoked in a new thread, sorry i have forgot to keep it same with NumberPicker, thank you for your notification and you can just use postInvalidate instead . i will modify NumberPickerView today, once finish i will let you know. thank you

**Comment by luizfp** [comment]
No problem. Thanks for the quick feedback and for the library. I'll be waiting for the update.

**Comment by Carbs0126** [comment]
So sorry for not updating in time.  Now you can try to update dependencies to 
```
    compile 'cn.carbswang.android:NumberPickerView:1.0.9'
```
i have made `onValueChanged` listeners invoked in main thread, and you can set the new attr  `app:npv_RespondChangeInMainThread="false"` i have added in 1.0.9 to false if you want to run `onValueChanged` listeners in sub thread.
and i have fix a bug "when change displayed values it is scrolling, the new displayed values may in malposition ".

sorry for updating late, and i love breaking bad too.

**Comment by luizfp** [comment]
We all love Breaking Bad! o/

I just tested the new release and now works properly. Thanks!
