### ISSUE TITLE
這個庫支援不連續的數字嗎？

### ISSUE THREAD

**Issue by siralam** [Carbs0126/NumberPickerView#50]
你好，沒想到你這個庫我已經用了兩個項目，這個需求在第三個項目才出現。

比如說我想用你的庫做一個時間的選擇器，分鐘只可以選 0  和 30，

那我基本上是這樣做：

```
        minutePicker.setDisplayedValues(new String[2]{"00", "30"});
        minutePicker.setMinValue(0);
        minutePicker.setMaxValue(30);
```

可是這樣會拋異常，因為你會檢查 (maxValue - mMinValue + 1 > mDisplayedValues.length)，如果為true會拋異常。這樣看來你好似只支援連續的數字，是這樣嗎？

(當然了我可以自己弄一個List，只監聽picker返回的position。是這樣嗎？)

**Comment by Carbs0126** [comment]
您好，感谢您的关注，很荣幸您采用这个控件。

您使用的方法和我设计的不太一致，所以您的这种使用方式是不合适的，您的代码：

`      minutePicker.setDisplayedValues(new String[2]{"00", "30"});
        minutePicker.setMinValue(0);
        minutePicker.setMaxValue(30);
`

实际上，我的这个setMinValue(0)  setMaxValue(30) 的意思是，第0个item的值为setMinValue(0)，第n个(最后一个) item的值为setMaxValue(n)，也就是说，minValue 至 maxValue 的值是每个item加一的。这样设计的使用场景是：比如我要选择年，从1900年开始，到2099年结束，此时，我就这样设置：
minutePicker.setDisplayedValues(new String[200]{"1900",“1901”，...., "2099"});
        minutePicker.setMinValue(0);//或者 0 + n
        minutePicker.setMaxValue(2099 - 1900);//如果是0 + n，那么这里就是 2099 - 1900 + n
也就是说，需要保证，maxValue-minValue的值等于或者小于 displayedValue的长度，即 maxValue减去minValue 的值代表的是 要显示出来的 item的数量，这样设计的好处是，如果用户想显示1900到1999，那么minValue不需要动，只需要setMaxValue为100就可以了。

不知道这样说，您是否理解了。minValue 、 maxValue 只代表开始item到最后item的索引。一般设置minValue为0

**Comment by siralam** [comment]
明白了，就是你的minValue和maxValue其實是代表position。

這樣我覺得這個命名頗誤導的，看你要不要考慮換掉囉。

**Comment by Carbs0126** [comment]
差不多就是代表position吧，min max 相减是显示的个数。
名字确实容易产生歧义，之前这么做主要是因为android原生的 NumberPicker 是这么设计的，他的api也是这样设计的，所以我就直接拿过来了，以便于适配。
