### ISSUE TITLE
How to align text to right?  如何将文本对齐？

### ISSUE THREAD

**Issue by henninghall** [Carbs0126/NumberPickerView#54]
Per default, the text is centered in the time picker. Is there a way to change the alignment to the left or right side? Thanks! 

默认情况下，文本在时间选择器中居中。有没有办法改变左侧或右侧的对齐方式？谢谢！

**Comment by Carbs0126** [comment]
very thoughtful for translation.
the text is painted by paint int NumberPickerView, you can check it in "onDraw( )" method in NumberPickerView.class .   maybe you can change the paint style by modifying  paint.setTextAlign(Paint.Align.Left);

**Comment by henninghall** [comment]
Thank you, I will have a look!

**Comment by henninghall** [comment]
@Carbs0126 If I manage to fix this, would you like a pull request for this feature?

**Comment by Carbs0126** [comment]
of course, i would like to accept your pull request

**Comment by nazimabdelaziz** [comment]
Hello does Align.Center work? 

I am using https://github.com/henninghall/react-native-date-picker which uses this library.
 When I set setTextAlign(Paint.Align.CENTER) it shows like this: 
![Screenshot from 2023-05-24 10-29-35](https://github.com/Carbs0126/NumberPickerView/assets/126457420/29419781-bd46-4621-83b7-a09cd2f81d75)

Thanks you.
