### ISSUE TITLE
How to change the Font?

### ISSUE THREAD

**Issue by stonestclair** [Carbs0126/NumberPickerView#56]
I don't know if I somehow missed it, but is there some way to change the font?

**Comment by Carbs0126** [comment]
you can use this method:

private void changeFont() {
        AssetManager assetManager = getAssets();
        Typeface tf = Typeface.createFromAsset(assetManager, "font/myfont.ttf");
        mNumberPickerView.setContentTextTypeface(tf);
        mNumberPickerView.setContentTextTypeface(tf);
        mNumberPickerView.postInvalidate();
    }
