### ISSUE TITLE
踩坑必看

### ISSUE THREAD

**Issue by Sunshine-Joex** [Carbs0126/NumberPickerView#57]
初始化数据和重新填充数据的时候，一定要调用 refreshByNewDisplayedValues
不要用 
 setDisplayedValues(datas);
 picker.setMinValue(minValue);
 picker.setMaxValue(maxValue);

**Comment by Carbs0126** [comment]
重新填充数据时，可以使用
setDisplayedValues(datas);
picker.setMinValue(minValue);
picker.setMaxValue(maxValue);
不过需要保证边界问题，如果填充的数据比之前的数量多，则先调用setDisplayedValues函数，再调用setMin setMax，反之先调用setMin setMax

其实完全可以参考NumberPicker的用法，之前api就是这么设计的
