### ISSUE TITLE
请问这个库还在维护吗

### ISSUE THREAD

**Issue by xiexiang89** [Carbs0126/NumberPickerView#58]

**Comment by Carbs0126** [comment]
感谢关注，偶尔维护一下子。遇到问题了吗？

**Comment by xiexiang89** [comment]
感谢你的控件和回复，跑过demo代码。暂时没有，想要自定义一些效果，类似ios的效果，文字有缩放大小效果

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: WangJianJun <notifications@github.com>
发送时间: Tuesday, May 14, 2019 8:50:02 PM
收件人: Carbs0126/NumberPickerView
抄送: xiexiang89; Author
主题: Re: [Carbs0126/NumberPickerView] 请问这个库还在维护吗 (#58)


感谢关注，偶尔维护一下子。遇到问题了吗？

―

**Comment by Carbs0126** [comment]
ios那种滚轮效果可能改动稍微大一点，主要的改动是在计算位置上和字体大小显示上，如有必要还需加上matrix计算。目前项目中没有做处理。

**Comment by xiexiang89** [comment]
其实是文字大小递减，显示5条数据，上下的文字大小递减

发自我的 iPhone

在 2019年5月14日，20:56，WangJianJun <notifications@github.com<mailto:notifications@github.com>> 写道：


ios那种滚轮效果可能改动稍微大一点，主要的改动是在计算位置上和字体大小显示上，如有必要还需加上matrix计算。目前项目中没有做处理。

**Comment by Carbs0126** [comment]
目前这个库就实现了文字大小的改变，可以控制最大最小字号。可能readme中的效果不是很明显，你clone下来跑跑就能看到效果了
