### ISSUE TITLE
两个NumberPickerView做联动并且第二个滚动并快速点击有个问题

### ISSUE THREAD

**Issue by caik13** [Carbs0126/NumberPickerView#60]
情况描述：两个NumberPickerView，内容都是  1,2,3,4,5，左边（NumberPickerView1）的滚动右边（NumberPickerView2）的自动滚动到左边的value + 1位置，
如果NumberPickerView2的value小于NumberPickerView1的，则NumberPickerView2自动滚动到NumberPickerView1的value +1位置。

遇到问题：当NumberPickerView2滑动到value比NumberPickerView1的value小的位置时，快速的点击一下NumberPickerView2，这是NumberPickerView2就会停在当前的位置，（NumberPickerView2的value比NumberPickerView1的value小代码里numberPickerView2.smoothScrollToValue(numberPickerView1.getValue() + 1)这样设置的，但是快速的点击一下就会导致代码失效）

**Comment by Carbs0126** [comment]
这个情景是，两个NumberPickerView联动，并且还要在联动期间响应手指点击。
当联动时（NumberPickerView2 自动响应 NumberPickerView1 时），此时如果有点击事件介入时，肯定会中止NumberPickerView2 的自动滑动的。
可以为NumberPickerView2加一个事件监听，在自动响应结束后再做手指响应

**Comment by caik13** [comment]
好的，感谢回复

**Comment by Carbs0126** [comment]
不客气
