### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by wangzhengcheng1994** [Carbs0126/NumberPickerView#66]
private int getWillPickIndexByGlobalY(int globalY){
        if(mItemHeight == 0) return 0;
        int willPickIndex = globalY / mItemHeight + mShowCount / 2;
        int index = getIndexByRawIndex(willPickIndex, getOneRecycleSize(), mWrapSelectorWheel && mWrapSelectorWheelCheck);
        if(0 <= index && index < getOneRecycleSize()){
            return index + mMinShowIndex;
        }else{
            throw new IllegalArgumentException("getWillPickIndexByGlobalY illegal index : " + index
                    + " getOneRecycleSize() : " + getOneRecycleSize() + " mWrapSelectorWheel : " + mWrapSelectorWheel);
        }
    }
测试过程中发现会抛出上述异常，很难复现，不是必现的。目前我也没有完整的复现过程，麻烦作者关注一下

**Comment by wangzhengcheng1994** [comment]
implementation 'cn.carbswang.android:NumberPickerView:1.1.1'
我依赖的是1.1.1 不确定其他版本是否存在该问题

**Comment by Carbs0126** [comment]
感谢您的反馈，目前最新版本是1.2.0，暂时使用这个版本看下吧，我稍后关注一下您反馈的这个问题，谢谢！
