### ISSUE TITLE
JCenter sunset is announced; please republish library version(s) to Maven Central

### ISSUE THREAD

**Issue by dejan2609** [Carbs0126/NumberPickerView#74]
**_Rationale_**: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Quote (from a link above):
> **_May 1st | Bintray, JCenter, GoCenter, and ChartCenter services will no longer be available_**

**_Note:_** it seems that Signal Android app depends on version 1.2.0 currently available only via JCenter:
https://mvnrepository.com/artifact/cn.carbswang.android/NumberPickerView/1.2.0

@Carbs0126 let me know if I can help you with this.

**Comment by simonpoole** [comment]
@Carbs0126 the read only version of jcenter is becoming more and more flaky, it would really be helpful if you could republish to MavenCentral. While not completely friction free, setting things up is a one time effort and afterwards publishing is easy.

**Comment by derekentringer** [comment]
@Carbs0126 Seeing the same issues as @simonpoole

**Comment by simonpoole** [comment]
Last try (because jcenter is going away even read-only) before a hard fork.

**Comment by NoelChew** [comment]
I am using Jitpack as a temporary solution.

1. add Jitpack to the list of repository source:
`maven { url 'https://jitpack.io' }`

2. use dependency from Jitpack
`implementation 'com.github.Carbs0126:NumberPickerView:master-SNAPSHOT'`

We can choose from the list of dependencies [here](https://jitpack.io/#Carbs0126/NumberPickerView).
Hope this is useful for some of us.

**Comment by dejan2609** [comment]
JCenter was closed on August 15th, 2024. Link: https://jfrog.com/blog/jcenter-sunset

I'll close this issue now (see comments above for solution(s)/workaround(s))
